# Generated by Django 4.2.9 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description_product_image_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shopping_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
