# Generated by Django 4.2.9 on 2026-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_shopping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
