# Generated by Django 4.2.9 on 2026-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartitem_shopping_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
