# Generated by Django 4.2.9 on 2026-04-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('modules', 'Modules'), ('sensors', 'Sensors'), ('microcontroller', 'Microcontroller'), ('components', 'Components')], default='modules', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shopping_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
