# Generated by Django 6.0.4 on 2026-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_product_type_alter_cartitem_shopping_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('none', 'None'), ('new', 'New Arrival'), ('off', '50% OFF'), ('limited', 'Limited'), ('out', 'Stock Out')], default='none', max_length=10),
        ),
    ]
