# Generated by Django 6.0.4 on 2026-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_best_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Best Sellers',
            },
        ),
        migrations.DeleteModel(
            name='best_seller',
        ),
    ]
