# Generated by Django 6.0.4 on 2026-04-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_bestsellers_delete_best_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestsellers',
            options={},
        ),
        migrations.RemoveField(
            model_name='bestsellers',
            name='products',
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
